import * as fs from 'fs-extra';
import * as path from 'path';
import * as stream from 'stream';
import * as readline from 'readline';
import {log} from '@serverless/utils/log';

const templates = [
    {
        "id": "APIG",
        "name": "API 网关服务 (APIG)",
        "content": "ewogICAgImJvZHkiOiAiIiwKICAgICJyZXF1ZXN0Q29udGV4dCI6IHsKICAgICAgICAiYXBpSWQiOiAiYmMxZGNmZmQtYWEzNS00NzRkLTg5N2MtZDUzNDI1YTRjMDhlIiwKICAgICAgICAicmVxdWVzdElkIjogIjExY2RjZGNmMzM5NDlkYzZkNzIyNjQwYTEzMDkxYzc3IiwKICAgICAgICAic3RhZ2UiOiAiUkVMRUFTRSIKICAgIH0sCiAgICAicXVlcnlTdHJpbmdQYXJhbWV0ZXJzIjogewogICAgICAgICJyZXNwb25zZVR5cGUiOiAiaHRtbCIKICAgIH0sCiAgICAiaHR0cE1ldGhvZCI6ICJHRVQiLAogICAgInBhdGhQYXJhbWV0ZXJzIjoge30sCiAgICAiaGVhZGVycyI6IHsKICAgICAgICAiYWNjZXB0LWxhbmd1YWdlIjogInpoLUNOLHpoO3E9MC44LHpoLVRXO3E9MC43LHpoLUhLO3E9MC41LGVuLVVTO3E9MC4zLGVuO3E9MC4yIiwKICAgICAgICAiYWNjZXB0LWVuY29kaW5nIjogImd6aXAsIGRlZmxhdGUsIGJyIiwKICAgICAgICAieC1mb3J3YXJkZWQtcG9ydCI6ICI0NDMiLAogICAgICAgICJ4LWZvcndhcmRlZC1mb3IiOiAiMTAzLjIxOC4yMTYuOTgiLAogICAgICAgICJhY2NlcHQiOiAidGV4dC9odG1sLGFwcGxpY2F0aW9uL3hodG1sK3htbCxhcHBsaWNhdGlvbi94bWw7cT0wLjksKi8qO3E9MC44IiwKICAgICAgICAidXBncmFkZS1pbnNlY3VyZS1yZXF1ZXN0cyI6ICIxIiwKICAgICAgICAiaG9zdCI6ICI1MGVlZGY5Mi1jOWFkLTRhYzAtODI3ZS1kN2MxMTQxNWQ0ZjEuYXBpZ3cuY24tbm9ydGgtMS5odWF3ZWljbG91ZC5jb20iLAogICAgICAgICJ4LWZvcndhcmRlZC1wcm90byI6ICJodHRwcyIsCiAgICAgICAgInByYWdtYSI6ICJuby1jYWNoZSIsCiAgICAgICAgImNhY2hlLWNvbnRyb2wiOiAibm8tY2FjaGUiLAogICAgICAgICJ4LXJlYWwtaXAiOiAiMTAzLjIxOC4yMTYuOTgiLAogICAgICAgICJ1c2VyLWFnZW50IjogIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgcnY6NTcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC81Ny4wIgogICAgfSwKICAgICJwYXRoIjogIi9hcGlnLWV2ZW50LXRlbXBsYXRlIiwKICAgICJpc0Jhc2U2NEVuY29kZWQiOiB0cnVlCn0="
    },
    {
        "id": "DEDICATEDGATEWAY",
        "name": "API 网关服务 (APIG专享版)",
        "content": "ewogICAgImJvZHkiOiAiIiwKICAgICJyZXF1ZXN0Q29udGV4dCI6IHsKICAgICAgICAiYXBpSWQiOiAiYmMxZGNmZmQtYWEzNS00NzRkLTg5N2MtZDUzNDI1YTRjMDhlIiwKICAgICAgICAicmVxdWVzdElkIjogIjExY2RjZGNmMzM5NDlkYzZkNzIyNjQwYTEzMDkxYzc3IiwKICAgICAgICAic3RhZ2UiOiAiUkVMRUFTRSIKICAgIH0sCiAgICAicXVlcnlTdHJpbmdQYXJhbWV0ZXJzIjogewogICAgICAgICJyZXNwb25zZVR5cGUiOiAiaHRtbCIKICAgIH0sCiAgICAiaHR0cE1ldGhvZCI6ICJHRVQiLAogICAgInBhdGhQYXJhbWV0ZXJzIjoge30sCiAgICAiaGVhZGVycyI6IHsKICAgICAgICAiYWNjZXB0LWxhbmd1YWdlIjogInpoLUNOLHpoO3E9MC44LHpoLVRXO3E9MC43LHpoLUhLO3E9MC41LGVuLVVTO3E9MC4zLGVuO3E9MC4yIiwKICAgICAgICAiYWNjZXB0LWVuY29kaW5nIjogImd6aXAsIGRlZmxhdGUsIGJyIiwKICAgICAgICAieC1mb3J3YXJkZWQtcG9ydCI6ICI0NDMiLAogICAgICAgICJ4LWZvcndhcmRlZC1mb3IiOiAiMTAzLjIxOC4yMTYuOTgiLAogICAgICAgICJhY2NlcHQiOiAidGV4dC9odG1sLGFwcGxpY2F0aW9uL3hodG1sK3htbCxhcHBsaWNhdGlvbi94bWw7cT0wLjksKi8qO3E9MC44IiwKICAgICAgICAidXBncmFkZS1pbnNlY3VyZS1yZXF1ZXN0cyI6ICIxIiwKICAgICAgICAiaG9zdCI6ICI1MGVlZGY5Mi1jOWFkLTRhYzAtODI3ZS1kN2MxMTQxNWQ0ZjEuYXBpZ3cuY24tbm9ydGgtMS5odWF3ZWljbG91ZC5jb20iLAogICAgICAgICJ4LWZvcndhcmRlZC1wcm90byI6ICJodHRwcyIsCiAgICAgICAgInByYWdtYSI6ICJuby1jYWNoZSIsCiAgICAgICAgImNhY2hlLWNvbnRyb2wiOiAibm8tY2FjaGUiLAogICAgICAgICJ4LXJlYWwtaXAiOiAiMTAzLjIxOC4yMTYuOTgiLAogICAgICAgICJ1c2VyLWFnZW50IjogIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgcnY6NTcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC81Ny4wIgogICAgfSwKICAgICJwYXRoIjogIi9hcGlnLWV2ZW50LXRlbXBsYXRlIiwKICAgICJpc0Jhc2U2NEVuY29kZWQiOiB0cnVlCn0="
    },
    {
        "id": "CTS",
        "name": "云审计服务 (CTS)",
        "content": "ewogICAgImN0cyI6IHsKICAgICAgICAidGltZSI6ICIyMDE4LzA2LzI2IDA4OjU0OjA3IEdNVCswODowMCIsCiAgICAgICAgInVzZXIiOiB7CiAgICAgICAgICAgICJuYW1lIjogInVzZXJOYW1lIiwKICAgICAgICAgICAgImlkIjogIjViNzI2YzRmYmZkODQ4MjFiYTg2NmJhZmFhZjU2YWF4IiwKICAgICAgICAgICAgImRvbWFpbiI6IHsKICAgICAgICAgICAgICAgICJuYW1lIjogImRvbWFpbk5hbWUiLAogICAgICAgICAgICAgICAgImlkIjogImIyYjM4NTNhZjQwNDQ4ZmNiOWU0MGR4ajg5NTA1YmEiCiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJyZXF1ZXN0Ijoge30sCiAgICAgICAgInJlc3BvbnNlIjoge30sCiAgICAgICAgImNvZGUiOiAyMDQsCiAgICAgICAgInNlcnZpY2VfdHlwZSI6ICJGdW5jdGlvbkdyYXBoIiwKICAgICAgICAicmVzb3VyY2VfdHlwZSI6ICJncmFwaCIsCiAgICAgICAgInJlc291cmNlX25hbWUiOiAid29ya2Zsb3ctMmJlMSIsCiAgICAgICAgInJlc291cmNlX2lkIjogInVybjpmZ3M6Y24tbm9ydGgteHh4OjJkMWQ4OTFkOTMwNTRiYmFhNjliOWU4NjZjMDk3MWFjOmdyYXBoOndvcmtmbG93LTJiZTEiLAogICAgICAgICJ0cmFjZV9uYW1lIjogImRlbGV0ZUdyYXBoIiwKICAgICAgICAidHJhY2VfdHlwZSI6ICJDb25zb2xlQWN0aW9uIiwKICAgICAgICAicmVjb3JkX3RpbWUiOiAiMjAxOC8wNi8yNiAwODo1NDowNyBHTVQrMDg6MDAiLAogICAgICAgICJ0cmFjZV9pZCI6ICI2OWJlNjRhNy0wMjMzLTExZTgtODJlNC1lNWQzNzkxMTE5M2UiLAogICAgICAgICJ0cmFjZV9zdGF0dXMiOiAibm9ybWFsIgogICAgfQp9"
    },
    {
        "id": "DDS",
        "name": "文档数据库服务 (DDS)",
        "content": "ewogICAgInJlY29yZHMiOiBbCiAgICAgICAgewogICAgICAgICAgICAiZXZlbnRfc291cmNlIjogImRkcyIsCiAgICAgICAgICAgICJldmVudF9uYW1lIjogImluc2VydCIsCiAgICAgICAgICAgICJyZWdpb24iOiAiY24tbm9ydGgteHgiLAogICAgICAgICAgICAiZXZlbnRfdmVyc2lvbiI6ICIxLjAiLAogICAgICAgICAgICAiZGRzIjogewogICAgICAgICAgICAgICAgInNpemVfYnl0ZXMiOiAiMTAwIiwKICAgICAgICAgICAgICAgICJ0b2tlbiI6ICJ7XCJfZGF0YVwiOiBcIjgyNUQ4QzJGNEQwMDAwMDAxNTI5Mjk1QTEwMDQ3NDAzOUEzNDEyQTY0QkE4OTA0MURDOTUyMzU3RkI0NDQ2NjQ1RjY5NjQwMDY0NUQ4QzJGOEU1QkVDQ0I2Q0Y1MzcwRDZBMDAwNFwifSIsCiAgICAgICAgICAgICAgICAiZnVsbF9kb2N1bWVudCI6ICJ7XCJfaWRcIjoge1wiJG9pZFwiOiBcIjVkOGMyZjhlNWJlY2NiNmNmNTM3MGQ2YVwifSxcIm5hbWVcIjogXCJkZHNcIixcImFnZVwiOiB7XCIkbnVtYmVyRG91YmxlXCI6IFwiNTIuMFwifX0iLAogICAgICAgICAgICAgICAgIm5zIjogIntcImRiXCI6IFwiZnVuY3Rpb25ncmFwaFwiLFwiY29sbFwiOiBcInBlcnNvblwifSIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgImV2ZW50X3NvdXJjZV9pZCI6ICJlNjA2NTg2MC1mN2I4LTRjY2EtODBiZC0yNGVmMmEzYmI3NDgiCiAgICAgICAgfQogICAgXQp9"
    },
    {
        "id": "GAUSSMONGO",
        "name": "云数据库 GaussDB (for Mongo)",
        "content": "ewogICAgInJlY29yZHMiOiBbCiAgICAgICAgewogICAgICAgICAgICAiZXZlbnRfbmFtZSI6ICJcImluc2VydFwiIiwKICAgICAgICAgICAgImV2ZW50X3ZlcnNpb24iOiAiMS4wIiwKICAgICAgICAgICAgImV2ZW50X3NvdXJjZSI6ICJnYXVzc19tb25nbyIsCiAgICAgICAgICAgICJyZWdpb24iOiAiY24tbm9ydGgteHgiLAogICAgICAgICAgICAiZ2F1c3NfbW9uZ28iOiB7CiAgICAgICAgICAgICAgICAiZnVsbF9kb2N1bWVudCI6ICJ7XCJfaWRcIjoge1wiJG9pZFwiOlwiNWY2MWRlOTQ0Nzc4ZGI1ZmNkZWQzZjg3XCJ9LFwiemhhbmdzYW5cIjogXCJ6aGFuZ3NhblwifSIsCiAgICAgICAgICAgICAgICAibnMiOiAie1wiZGJcIjogXCJ6aGFuZ3NhblwiLFwiY29sbFwiOiBcInpoYW5nc2FuXCJ9IiwKICAgICAgICAgICAgICAgICJzaXplX2J5dGVzIjogIjEwMCIsCiAgICAgICAgICAgICAgICAidG9rZW4iOiAie1wiX2RhdGFcIjogXCI4MjVGNjFERTk0MDAwMDAwMDEyOTI5NUExMDA0QTJEOUFFNjEyMDZDNDNBNUFGNDdDQUY3QzVDMDBDNTk0NjY0NUY2OTY0MDA2NDVGNjFERTk0NDc3OERCNUZDREVEM0Y4NzAwMDRcIn0iCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJldmVudF9zb3VyY2VfaWQiOiAiNTExNTNkMTktMmI3ZC00MDJjLTlhNzktNzU3MTYzMjU4YTM2IgogICAgICAgIH0KICAgIF0sCiAgICAidmVybmllciI6ICJ7XCJfZGF0YVwiOiBcIjgyNUY2MURFOTQwMDAwMDAwMTI5Mjk1QTEwMDRBMkQ5QUU2MTIwNkM0M0E1QUY0N0NBRjdDNUMwMEM1OTQ2NjQ1RjY5NjQwMDY0NUY2MURFOTQ0Nzc4REI1RkNERUQzRjg3MDAwNFwifSIKfQ=="
    },
    {
        "id": "DIS",
        "name": "数据接入服务 (DIS)",
        "content": "ewogICAgIlNoYXJkSUQiOiAic2hhcmRJZC0wMDAwMDAwMDAwIiwKICAgICJNZXNzYWdlIjogewogICAgICAgICJuZXh0X3BhcnRpdGlvbl9jdXJzb3IiOiAiZXlKblpYUkpkR1Z5WVhSdmNsQmhjbUZ0SWpwN0luTjBjbVZoYlMxdVlXMWxJam9pWkdsekxYTjNkR1Z6ZENJc0luQmhjblJwZEdsdmJpMXBaQ0k2SW5Ob1lYSmtTV1F0TURBd01EQXdNREF3TUNJc0ltTjFjbk52Y2kxMGVYQmxJam9pVkZKSlRWOUlUMUpKV2s5T0lpd2ljM1JoY25ScGJtY3RjMlZ4ZFdWdVkyVXRiblZ0WW1WeUlqb2lOQ0o5TENKblpXNWxjbUYwWlZScGJXVnpkR0Z0Y0NJNk1UVXdPVFl3TmpNNU1qRTVNWDAiLAogICAgICAgICJyZWNvcmRzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAicGFydGl0aW9uX2tleSI6ICJzaGFyZElkXzAwMDAwMDAwMDAiLAogICAgICAgICAgICAgICAgImRhdGEiOiAiZDJWc1kyOXRaUT09IiwKICAgICAgICAgICAgICAgICJzZXF1ZW5jZV9udW1iZXIiOiAiMCIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgInBhcnRpdGlvbl9rZXkiOiAic2hhcmRJZF8wMDAwMDAwMDAwIiwKICAgICAgICAgICAgICAgICJkYXRhIjogImRYTnBibWM9IiwKICAgICAgICAgICAgICAgICJzZXF1ZW5jZV9udW1iZXIiOiAiMSIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgInBhcnRpdGlvbl9rZXkiOiAic2hhcmRJZF8wMDAwMDAwMDAwIiwKICAgICAgICAgICAgICAgICJkYXRhIjogIlJuVnVZM1JwYjI1VGRHRm5aUT09IiwKICAgICAgICAgICAgICAgICJzZXF1ZW5jZV9udW1iZXIiOiAiMiIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgInBhcnRpdGlvbl9rZXkiOiAic2hhcmRJZF8wMDAwMDAwMDAwIiwKICAgICAgICAgICAgICAgICJkYXRhIjogImMyVnlkbWxqWlE9PSIsCiAgICAgICAgICAgICAgICAic2VxdWVuY2VfbnVtYmVyIjogIjMiCiAgICAgICAgICAgIH0KICAgICAgICBdLAogICAgICAgICJtaWxsaXNfYmVoaW5kX2xhdGVzdCI6ICIiCiAgICB9LAogICAgIlRhZyI6ICJsYXRlc3QiLAogICAgIlN0cmVhbU5hbWUiOiAiZGlzLXN3dGVzdCIKfQ=="
    },
    {
        "id": "LTS",
        "name": "云日志服务 (LTS)",
        "content": "ewogICAgImx0cyI6IHsKICAgICAgICAiZGF0YSI6ICJleUpzYjJkeklqb2lXM3RjSW0xbGMzTmhaMlZjSWpwY0lqSXdNVGd0TURndE1EZ3ZNRGc2TURnNk1EZ2dXMWRTVGwwZ1czUmxjM1F1WjI4Nk1EaGRWR2hwY3lCcGN5QmhJSFJsYzNRZ2JXVnpjMkZuWlM1Y0lpeGNJblJwYldWY0lqb3hOVE13TURBNU5qVXpNRFU1TEZ3aWFHOXpkRjl1WVcxbFhDSTZYQ0psWTNNdGRHVnpkRndpTEZ3aWFYQmNJanBjSWpFNU1pNHhOamd1TVM0eFhDSXNYQ0p3WVhSb1hDSTZYQ0oyWVhJdmJHOW5MM1JsYzNRdWJHOW5YQ0lzWENKc2IyZGZkV2xrWENJNlhDSTJOak5rTmprek1DMDNPVEprTFRFeFpUZ3RPR0l3T0MweU9EWmxaRFE0T0dObE56QmNJaXhjSW14cGJtVmZibTljSWpveGZWMGlMQ0p2ZDI1bGNpSTZJall5T0RCbE1UY3dZbVE1TXpSbU5qQmhOR1E0TlRGalpqVmpZVEExTVRJNUlpd2liRzluWDJkeWIzVndYMmxrSWpvaU9UZGhPV1F5T0RRdE5EUTBPQzB4TVdVNExUaG1ZVFF0TWpnMlpXUTBPRGhqWlRjd0lpd2liRzluWDNSdmNHbGpYMmxrSWpvaU1XRTVOamMxWVRjdE56ZzBaQzB4TVdVNExUbG1OekF0TWpnMlpXUTBPRGhqWlRjd0luMD0iCiAgICB9Cn0="
    },
    {
        "id": "OBS",
        "name": "对象存储服务 (OBS)",
        "content": "ewogICAgIlJlY29yZHMiOiBbCiAgICAgICAgewogICAgICAgICAgICAiZXZlbnRWZXJzaW9uIjogIjIuMCIsCiAgICAgICAgICAgICJldmVudFRpbWUiOiAiMjAxOC0wMS0wOVQwNzo1MDo1MC4wMjhaIiwKICAgICAgICAgICAgInJlcXVlc3RQYXJhbWV0ZXJzIjogewogICAgICAgICAgICAgICAgInNvdXJjZUlQQWRkcmVzcyI6ICIxMDMuMjE4LjIxNi4xMjUiCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJzMyI6IHsKICAgICAgICAgICAgICAgICJjb25maWd1cmF0aW9uSWQiOiAiVUsxREdGUFlVS1VaRkhOUTAwMDAwMTYwQ0MwQjQ3MUQxMDFFRDMwQ0UyNERGNERCIiwKICAgICAgICAgICAgICAgICJvYmplY3QiOiB7CiAgICAgICAgICAgICAgICAgICAgImVUYWciOiAiOWQzNzdiMTBjZTc3OGM0OTM4YjNjN2UyYzYzYTIyOWEiLAogICAgICAgICAgICAgICAgICAgICJzZXF1ZW5jZXIiOiAiMDAwMDAwMDAxNjBEOUU2ODE0ODRENkI0QzAwMDAwMDAiLAogICAgICAgICAgICAgICAgICAgICJrZXkiOiAiam9iLnBuZyIsCiAgICAgICAgICAgICAgICAgICAgInNpemUiOiA3Nzc4MzUKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiYnVja2V0IjogewogICAgICAgICAgICAgICAgICAgICJhcm4iOiAiYXJuOmZzczpzMzo6OnN5ai1pbnB1dDIiLAogICAgICAgICAgICAgICAgICAgICJuYW1lIjogImZ1bmN0aW9uc3RvcmFnZS10ZW1wbGF0ZSIsCiAgICAgICAgICAgICAgICAgICAgIm93bmVySWRlbnRpdHkiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJQcmluY2lwYWxJZCI6ICIwZWQxYjczNDczZjI0MTM0YTQ3ODk2MmU2MzE2NTFlYiIKICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJhd3NSZWdpb24iOiAiY24tbm9ydGgteHgiLAogICAgICAgICAgICAiZXZlbnROYW1lIjogIk9iamVjdENyZWF0ZWQ6UG9zdCIsCiAgICAgICAgICAgICJ1c2VySWRlbnRpdHkiOiB7CiAgICAgICAgICAgICAgICAicHJpbmNpcGFsSWQiOiAiOWJmNDM3ODliMWZmNGI2NzkwNDBmMzVjYzRmMGRjMDUiCiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICBdCn0="
    },
    {
        "id": "SMN",
        "name": "消息通知服务 (SMN)",
        "content": "ewogICAgInJlY29yZCI6IFsKICAgICAgICB7CiAgICAgICAgICAgICJldmVudF92ZXJzaW9uIjogIjEuMCIsCiAgICAgICAgICAgICJzbW4iOiB7CiAgICAgICAgICAgICAgICAidG9waWNfdXJuIjogInVybjpzbW46Y24tbm9ydGgteHg6MDE2MmMwZjIyMDI4NDY5OGI3N2EzZDI2NDM3NjM0M2E6dGVzdDMiLAogICAgICAgICAgICAgICAgInRpbWVzdGFtcCI6ICIyMDE4LTAxLTA5VDA3OjExOjQwWiIsCiAgICAgICAgICAgICAgICAibWVzc2FnZV9hdHRyaWJ1dGVzIjogbnVsbCwKICAgICAgICAgICAgICAgICJtZXNzYWdlIjogInRoaXMgaXMgc21uIG1lc3NhZ2UgY29udGVudCIsCiAgICAgICAgICAgICAgICAidHlwZSI6ICJub3RpZmljYXRpb24iLAogICAgICAgICAgICAgICAgIm1lc3NhZ2VfaWQiOiAiYTUxNjcxZjc3ZDRhNDc5Y2FjYjA5ZTJjZDU5MWE5ODMiLAogICAgICAgICAgICAgICAgInN1YmplY3QiOiAidGhpcyBpcyBzbW4gbWVzc2FnZSBzdWJqZWN0IgogICAgICAgICAgICB9LAogICAgICAgICAgICAiZXZlbnRfc3Vic2NyaXB0aW9uX3VybiI6ICJ1cm46ZnNzOmNuLW5vcnRoLXh4OjAxNjJjMGYyMjAyODQ2OThiNzdhM2QyNjQzNzYzNDNhOmZ1bmN0aW9uOmRlZmF1bHQ6cmVhZC1zbW4tbWVzc2FnZTpsYXRlc3QiLAogICAgICAgICAgICAiZXZlbnRfc291cmNlIjogInNtbiIKICAgICAgICB9CiAgICBdLAogICAgImZ1bmN0aW9ubmFtZSI6ICJ0ZXN0IiwKICAgICJyZXF1ZXN0SWQiOiAiN2MzMDdmNmEtY2Y2OC00ZTY1LThiZTAtNGM3NzQwNWExYjJjIiwKICAgICJ0aW1lc3RhbXAiOiAiVHVlIEphbiAwOSAyMDE4IDE1OjExOjQwIEdNVCswODAwIChDU1QpIgp9"
    },
    {
        "id": "TIMER",
        "name": "定时触发器 (TIMER)",
        "content": "ewogICAgInZlcnNpb24iOiAidjIuMCIsCiAgICAidGltZSI6ICIyMDIzLTA2LTAxVDA4OjMwOjAwKzA4OjAwIiwKICAgICJ0cmlnZ2VyX3R5cGUiOiAiVElNRVIiLAogICAgInRyaWdnZXJfbmFtZSI6ICJUaW1lcl8wMDEiLAogICAgInVzZXJfZXZlbnQiOiAiVXNlciBFdmVudCIKfQ=="
    },
    {
        "id": "KAFKA",
        "name": "分布式消息服务 Kafka版",
        "content": "ewogICAgImV2ZW50X3ZlcnNpb24iOiAidjEuMCIsCiAgICAiZXZlbnRfdGltZSI6IDE1NzY3Mzc5NjIsCiAgICAidHJpZ2dlcl90eXBlIjogIktBRktBIiwKICAgICJyZWdpb24iOiAiY24tbm9ydGgteHgiLAogICAgImluc3RhbmNlX2lkIjogIjgxMzM1ZDU2LWI5ZmUtNDY3OS1iYTk1LTcwMzA5NDljYzc2YiIsCiAgICAicmVjb3JkcyI6IFsKICAgICAgICB7CiAgICAgICAgICAgICJtZXNzYWdlcyI6IFsKICAgICAgICAgICAgICAgICJrYWZrYSBtZXNzYWdlMSIsCiAgICAgICAgICAgICAgICAia2Fma2EgbWVzc2FnZTIiLAogICAgICAgICAgICAgICAgImthZmthIG1lc3NhZ2UzIiwKICAgICAgICAgICAgICAgICJrYWZrYSBtZXNzYWdlNCIsCiAgICAgICAgICAgICAgICAia2Fma2EgbWVzc2FnZTUiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJ0b3BpY19pZCI6ICJ0b3BpYy10ZXN0IgogICAgICAgIH0KICAgIF0KfQ=="
    },
    {
        "id": "OPENSOURCEKAFKA",
        "name": "Kafka (OPENSOURCEKAFKA)",
        "content": "ewogICAgImV2ZW50X3ZlcnNpb24iOiAidjEuMCIsCiAgICAiZXZlbnRfdGltZSI6IDE1NzY3Mzc5NjIsCiAgICAidHJpZ2dlcl90eXBlIjogIktBRktBIiwKICAgICJyZWdpb24iOiAiY24tbm9ydGgteHgiLAogICAgImluc3RhbmNlX2lkIjogIjgxMzM1ZDU2LWI5ZmUtNDY3OS1iYTk1LTcwMzA5NDljYzc2YiIsCiAgICAicmVjb3JkcyI6IFsKICAgICAgICB7CiAgICAgICAgICAgICJtZXNzYWdlcyI6IFsKICAgICAgICAgICAgICAgICJrYWZrYSBtZXNzYWdlMSIsCiAgICAgICAgICAgICAgICAia2Fma2EgbWVzc2FnZTIiLAogICAgICAgICAgICAgICAgImthZmthIG1lc3NhZ2UzIiwKICAgICAgICAgICAgICAgICJrYWZrYSBtZXNzYWdlNCIsCiAgICAgICAgICAgICAgICAia2Fma2EgbWVzc2FnZTUiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJ0b3BpY19pZCI6ICJ0b3BpYy10ZXN0IgogICAgICAgIH0KICAgIF0KfQ=="
    },
    {
        "id": "IOTEDGE",
        "name": "IoT边缘服务(IoTEdge)",
        "content": "ewogICAgInNlcnZpY2VzIjogWwogICAgICAgIHsKICAgICAgICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgICAgICAgICAidGVtcCI6IDIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInNlcnZpY2VfaWQiOiAic2Vuc29yIiwKICAgICAgICAgICAgImV2ZW50X3RpbWUiOiAiMjAyMS0wMi0xMlQxMjoxMjoxMi4wMDBaIgogICAgICAgIH0KICAgIF0sCiAgICAiZGV2aWNlX2lkIjogInRlc3Rfc2VydmVybGVzc19kZXZpY2VfMSIsCiAgICAicHJvZHVjdF9pZCI6ICI2NDc1OThhMGU2ZjE0OTVjYTIxNTRiMjMiCn0="
    },
    {
        "id": "RABBITMQ",
        "name": "分布式消息服务 RabbitMQ版",
        "content": "ewogICAgImV2ZW50X3ZlcnNpb24iOiAidjEuMCIsCiAgICAiZXZlbnRfdGltZSI6IDE1NzY3Mzc5NjIsCiAgICAidHJpZ2dlcl90eXBlIjogIlJBQkJJVE1RIiwKICAgICJyZWdpb24iOiAieHgteHh4eC14IiwKICAgICJyZWNvcmRzIjogWwogICAgICAgIHsKICAgICAgICAgICAgIm1lc3NhZ2VzIjogWwogICAgICAgICAgICAgICAgInJhYmJpdG1xIG1lc3NhZ2UxIiwKICAgICAgICAgICAgICAgICJyYWJiaXRtcSBtZXNzYWdlMiIsCiAgICAgICAgICAgICAgICAicmFiYml0bXEgbWVzc2FnZTMiLAogICAgICAgICAgICAgICAgInJhYmJpdG1xIG1lc3NhZ2U0IiwKICAgICAgICAgICAgICAgICJyYWJiaXRtcSBtZXNzYWdlNSIKICAgICAgICAgICAgXSwKICAgICAgICAgICAgImluc3RhbmNlX2lkIjogIjgxMzM1ZDU2LWI5ZmUtNDY3OS1iYTk1LTcwMzA5NDljYzc2YiIsCiAgICAgICAgICAgICJleGNoYW5nZSI6ICJleGNoYW5nZS10ZXN0IgogICAgICAgIH0KICAgIF0KfQ=="
    },
    {
        "id": "EGRABBITMQ",
        "name": "分布式消息服务 RabbitMQ版 (EventGrid)",
        "content": "ewogICAgImRhdGFjb250ZW50dHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIiwKICAgICJkYXRhIjogewogICAgICAgICJjb250ZXh0IjogInl5eXl5IgogICAgfSwKICAgICJzdWJqZWN0IjogIlJBQkJJVE1ROnJlZ2lvbjpkb21haW5JZC9wcm9qZWN0SWQ6UkFCQklUTVE6ZXZlbnRTb3VyY2VOYW1lIiwKICAgICJzcGVjdmVyc2lvbiI6ICIxLjAiLAogICAgImlkIjogIjAxNmQ1YmQzLTYyMzEtNGU5ZS04NmVmLWU0NTFhMDcwZDU5OCIsCiAgICAic291cmNlIjogImV2ZW50U291cmNlTmFtZSIsCiAgICAidGltZSI6ICIyMDIzLTA0LTA3VDExOjUxOjEwWiIsCiAgICAidHlwZSI6ICJSQUJCSVRNUTpDbG91ZFRyYWNlOlJhYmJpdG1xQ2FsbCIKfQ=="
    },
    {
        "id": "EGROCKETMQ",
        "name": "分布式消息服务 RocketMQ版 (EventGrid)",
        "content": "ewogICAgImRhdGFjb250ZW50dHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIiwKICAgICJkYXRhIjogewogICAgICAgICJjb250ZXh0IjogInl5eXl5IgogICAgfSwKICAgICJzdWJqZWN0IjogIlJPQ0tFVE1ROnJlZ2lvbjpkb21haW5JZC9wcm9qZWN0SWQ6Uk9DS0VUTVE6ZXZlbnRTb3VyY2VOYW1lIiwKICAgICJzcGVjdmVyc2lvbiI6ICIxLjAiLAogICAgImlkIjogIjAxNmQ1YmQzLTYyMzEtNGU5ZS04NmVmLWU0NTFhMDcwZDU5OCIsCiAgICAic291cmNlIjogImV2ZW50U291cmNlTmFtZSIsCiAgICAidGltZSI6ICIyMDIzLTA0LTA3VDExOjUxOjEwWiIsCiAgICAidHlwZSI6ICJST0NLRVRNUTpDbG91ZFRyYWNlOlJvY2tldG1xQ2FsbCIKfQ=="
    },
    {
        "id": "black",
        "name": "空白模板",
        "content": "eyJrZXkiOiAidmFsdWUifQ=="
    },
    {
        "id": "loginSecurity",
        "name": "登录安全实时分析",
        "content": "ewoJImN0cyI6IHsKCQkicmVzb3VyY2VfbmFtZSI6ICJ0ZXN0bmFtZSIsCgkJInRyYWNlX3JhdGluZyI6ICJub3JtYWwiLAoJCSJyZWNvcmRfdGltZSI6IDE1MzI0MzEzOTEwMDAsCgkJInJlc291cmNlX2lkIjogIjdmNjU0YTM1MjM4MTQ1Yjg4OTQ2MGQ0N2FhZTIxZDBmIiwKCQkidHJhY2VfbmFtZSI6ICJsb2dpbiIsCgkJInNvdXJjZV9pcCI6ICIxOTIuNjUuNTYuMTM5IiwKCQkidHJhY2VfaWQiOiAiZmZiOWYwODAtOGYzMy0xMWU4LWJiYTgtMjg2ZWQ0ODhkZWIzIiwKCQkidHJhY2Vfc3RhdHVzIjogIm5vcm1hbCIsCgkJImNvZGUiOiAzMDIsCgkJInVzZXIiOiB7CgkJCSJkb21haW4iOiB7CgkJCQkibmFtZSI6ICJ0ZXN0bmFtZSIsCgkJCQkiaWQiOiAiNzgxNjkxOTg0NDVlNDF4NDlhdDE3ODE2MTY1YjA2MiIKCQkJfSwKCQkJIm5hbWUiOiAidGVzdG5hbWUiLAoJCQkiaWQiOiAiNzgxNjkxOTg0NDVlNDF4NDlhdDE3ODE2MTY1YjA2MiIKCQl9LAoJCSJ0aW1lIjogMTUzMjQzMTQxMzEyOCwKCQkic2VydmljZV90eXBlIjogIklBTSIsCgkJInRyYWNlX3R5cGUiOiAiQ29uc29sZUFjdGlvbiIsCgkJInJlc3BvbnNlIjoge30sCgkJInJlc291cmNlX3R5cGUiOiAidXNlciIsCgkJInJlcXVlc3QiOiB7fQoJfQp9"
    },
    {
        "id": "imageTag",
        "name": "图片分类",
        "type": "event",
        "content": "ewogICAgIlJlY29yZHMiOiBbCiAgICAgICAgewogICAgICAgICAgICAiZXZlbnRWZXJzaW9uIjogIjIuMCIsCiAgICAgICAgICAgICJldmVudFRpbWUiOiAiMjAxOC0wMS0wOVQwNzo1MDo1MC4wMjhaIiwKICAgICAgICAgICAgInJlcXVlc3RQYXJhbWV0ZXJzIjogewogICAgICAgICAgICAgICAgInNvdXJjZUlQQWRkcmVzcyI6ICIxMDMuMjE4LjIxNi4xMjUiCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJzMyI6IHsKICAgICAgICAgICAgICAgICJjb25maWd1cmF0aW9uSWQiOiAiVUsxREdGUFlVS1VaRkhOUTAwMDAwMTYwQ0MwQjQ3MUQxMDFFRDMwQ0UyNERGNERCIiwKICAgICAgICAgICAgICAgICJvYmplY3QiOiB7CiAgICAgICAgICAgICAgICAgICAgImVUYWciOiAiOWQzNzdiMTBjZTc3OGM0OTM4YjNjN2UyYzYzYTIyOWEiLAogICAgICAgICAgICAgICAgICAgICJzZXF1ZW5jZXIiOiAiMDAwMDAwMDAxNjBEOUU2ODE0ODRENkI0QzAwMDAwMDAiLAogICAgICAgICAgICAgICAgICAgICJrZXkiOiAiam9iLnBuZyIsCiAgICAgICAgICAgICAgICAgICAgInNpemUiOiA3Nzc4MzUKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiYnVja2V0IjogewogICAgICAgICAgICAgICAgICAgICJhcm4iOiAiYXJuOmZzczpzMzo6OnN5ai1pbnB1dDIiLAogICAgICAgICAgICAgICAgICAgICJuYW1lIjogImZ1bmN0aW9uc3RvcmFnZS10ZW1wbGF0ZSIsCiAgICAgICAgICAgICAgICAgICAgIm93bmVySWRlbnRpdHkiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJQcmluY2lwYWxJZCI6ICIwZWQxYjczNDczZjI0MTM0YTQ3ODk2MmU2MzE2NTFlYiIKICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJhd3NSZWdpb24iOiAiY24tbm9ydGgteHh4IiwKICAgICAgICAgICAgImV2ZW50TmFtZSI6ICJPYmplY3RDcmVhdGVkOlBvc3QiLAogICAgICAgICAgICAidXNlcklkZW50aXR5IjogewogICAgICAgICAgICAgICAgInByaW5jaXBhbElkIjogIjliZjQzNzg5YjFmZjRiNjc5MDQwZjM1Y2M0ZjBkYzA1IgogICAgICAgICAgICB9CiAgICAgICAgfQogICAgXQp9"
    },
    {
        "id": "pornImageAnalysis",
        "name": "图片鉴黄",
        "content": "ewogICAgImJvZHkiOiAiZXdvZ0lDQWdJblZ5YkNJNklDSm9kSFJ3Y3pvdkwySnFZblZqYTJWMExtOWljeTV0ZVdoM1kyeHZkV1J6TG1OdmJTODNNRGt5TXpReE1TNXFjR2NpTEFvZ0lDQWdJbWx0WVdkbElqb2dJaUlLZlE9PSIsCiAgICAicmVxdWVzdENvbnRleHQiOiB7CiAgICAgICAgImFwaUlkIjogImJjMWRjZmZkLWFhMzUtNDc0ZC04OTdjLWQ1MzQyNWE0YzA4ZSIsCiAgICAgICAgInJlcXVlc3RJZCI6ICIxMWNkY2RjZjMzOTQ5ZGM2ZDcyMjY0MGExMzA5MWM3NyIsCiAgICAgICAgInN0YWdlIjogIlJFTEVBU0UiCiAgICB9LAogICAgInF1ZXJ5U3RyaW5nUGFyYW1ldGVycyI6IHsKICAgICAgICAicmVzcG9uc2VUeXBlIjogImh0bWwiCiAgICB9LAogICAgImh0dHBNZXRob2QiOiAiUE9TVCIsCiAgICAicGF0aFBhcmFtZXRlcnMiOiB7fSwKICAgICJoZWFkZXJzIjogewogICAgICAgICJhY2NlcHQtbGFuZ3VhZ2UiOiAiemgtQ04semg7cT0wLjgsemgtVFc7cT0wLjcsemgtSEs7cT0wLjUsZW4tVVM7cT0wLjMsZW47cT0wLjIiLAogICAgICAgICJhY2NlcHQtZW5jb2RpbmciOiAiZ3ppcCwgZGVmbGF0ZSwgYnIiLAogICAgICAgICJ4LWZvcndhcmRlZC1wb3J0IjogIjQ0MyIsCiAgICAgICAgIngtZm9yd2FyZGVkLWZvciI6ICIxMDMuMjE4LjIxNi45OCIsCiAgICAgICAgImFjY2VwdCI6ICJ0ZXh0L2h0bWwsYXBwbGljYXRpb24veGh0bWwreG1sLGFwcGxpY2F0aW9uL3htbDtxPTAuOSwqLyo7cT0wLjgiLAogICAgICAgICJ1cGdyYWRlLWluc2VjdXJlLXJlcXVlc3RzIjogIjEiLAogICAgICAgICJob3N0IjogIjUwZWVkZjkyLWM5YWQtNGFjMC04MjdlLWQ3YzExNDE1ZDRmMS5hcGlndy5jbi1ub3J0aC0xLmh1YXdlaWNsb3VkLmNvbSIsCiAgICAgICAgIngtZm9yd2FyZGVkLXByb3RvIjogImh0dHBzIiwKICAgICAgICAicHJhZ21hIjogIm5vLWNhY2hlIiwKICAgICAgICAiY2FjaGUtY29udHJvbCI6ICJuby1jYWNoZSIsCiAgICAgICAgIngtcmVhbC1pcCI6ICIxMDMuMjE4LjIxNi45OCIsCiAgICAgICAgInVzZXItYWdlbnQiOiAiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0OyBydjo1Ny4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzU3LjAiCiAgICB9LAogICAgInBhdGgiOiAiL2FwaWctZXZlbnQtdGVtcGxhdGUiLAogICAgImlzQmFzZTY0RW5jb2RlZCI6IHRydWUKfQ=="
    },
    {
        "id": "voiceAnalysis",
        "name": "语音识别",
        "content": "ewogICAgImJvZHkiOiAiZXdvZ0lDQWdJblZ5YkNJNklDSm9kSFJ3Y3pvdkwyRnBMV1JsYlc4dWIySnpMbTE1YUhkamJHOTFaSE11WTI5dEx6RXpNelkwT1M1M1lYWWlMQW9nSUNBZ0luWnZhV05sSWpvZ0lpSXNDaUFnSUNBaWMyRnRjR3hsWDNKaGRHVWlPaUFpTVRacklncDkiLAogICAgInJlcXVlc3RDb250ZXh0IjogewogICAgICAgICJhcGlJZCI6ICJiYzFkY2ZmZC1hYTM1LTQ3NGQtODk3Yy1kNTM0MjVhNGMwOGUiLAogICAgICAgICJyZXF1ZXN0SWQiOiAiMTFjZGNkY2YzMzk0OWRjNmQ3MjI2NDBhMTMwOTFjNzciLAogICAgICAgICJzdGFnZSI6ICJSRUxFQVNFIgogICAgfSwKICAgICJxdWVyeVN0cmluZ1BhcmFtZXRlcnMiOiB7CiAgICAgICAgInJlc3BvbnNlVHlwZSI6ICJodG1sIgogICAgfSwKICAgICJodHRwTWV0aG9kIjogIlBPU1QiLAogICAgInBhdGhQYXJhbWV0ZXJzIjoge30sCiAgICAiaGVhZGVycyI6IHsKICAgICAgICAiYWNjZXB0LWxhbmd1YWdlIjogInpoLUNOLHpoO3E9MC44LHpoLVRXO3E9MC43LHpoLUhLO3E9MC41LGVuLVVTO3E9MC4zLGVuO3E9MC4yIiwKICAgICAgICAiYWNjZXB0LWVuY29kaW5nIjogImd6aXAsIGRlZmxhdGUsIGJyIiwKICAgICAgICAieC1mb3J3YXJkZWQtcG9ydCI6ICI0NDMiLAogICAgICAgICJ4LWZvcndhcmRlZC1mb3IiOiAiMTAzLjIxOC4yMTYuOTgiLAogICAgICAgICJhY2NlcHQiOiAidGV4dC9odG1sLGFwcGxpY2F0aW9uL3hodG1sK3htbCxhcHBsaWNhdGlvbi94bWw7cT0wLjksKi8qO3E9MC44IiwKICAgICAgICAidXBncmFkZS1pbnNlY3VyZS1yZXF1ZXN0cyI6ICIxIiwKICAgICAgICAiaG9zdCI6ICI1MGVlZGY5Mi1jOWFkLTRhYzAtODI3ZS1kN2MxMTQxNWQ0ZjEuYXBpZ3cuY24tbm9ydGgtMS5odWF3ZWljbG91ZC5jb20iLAogICAgICAgICJ4LWZvcndhcmRlZC1wcm90byI6ICJodHRwcyIsCiAgICAgICAgInByYWdtYSI6ICJuby1jYWNoZSIsCiAgICAgICAgImNhY2hlLWNvbnRyb2wiOiAibm8tY2FjaGUiLAogICAgICAgICJ4LXJlYWwtaXAiOiAiMTAzLjIxOC4yMTYuOTgiLAogICAgICAgICJ1c2VyLWFnZW50IjogIk1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgcnY6NTcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC81Ny4wIgogICAgfSwKICAgICJwYXRoIjogIi9hcGlnLWV2ZW50LXRlbXBsYXRlIiwKICAgICJpc0Jhc2U2NEVuY29kZWQiOiB0cnVlCn0="
    }
];

export class EventService {
    getEvent(argsData: any): Promise<string> {
        let input: any;
        if (argsData?.eventStdin) {
            log.notice(`Reading event data from stdin, which can be ended with Enter then Ctrl+D
  (you can also pass it from file with -e)`);
            input = process.stdin;
        } else if (argsData?.eventFile) {
            input = fs.createReadStream(this.getEventPath(argsData.eventFile), {
                encoding: 'utf-8'
            });
        } else if (argsData?.data) {
            input = stream.Readable.from(argsData.data);
        } else {
            input = stream.Readable.from(this.getEventTemplate(argsData.eventName));
        }
        return new Promise((resolve, reject) => {
            const rl = readline.createInterface({
                input,
                output: process.stdout
            });

            let event = '';
            rl.on('line', (line) => {
                event += line;
            });
            rl.on('close', () => {
                log.notice();
                resolve(event);
            });

            rl.on('SIGINT', function () {
                reject(new Error('^C'));
            });
        });
    }

    /**
     * 获取事件模板文件
     * @param filePath 
     * @returns 
     */
    private getEventPath(filePath: string) {
        if (!fs.pathExistsSync(filePath)) { // 文件不存在
            throw new Error('The file you provided does not exist.');
        }
        if (path.isAbsolute(filePath)) {
            return filePath;
        }
        return path.resolve(process.cwd(), filePath);
    }

    /**
     * 获取模板信息
     * @param name 测试事件名称
     * @returns 
     */
    private getEventTemplate(name = 'black') {
        const temp = templates.find(t => t.id === name) ?? templates.find(t => t.id === 'black');
        if (temp?.content) {
            return Buffer.from(temp.content, 'base64').toString('utf-8');
        }
        return Buffer.from('eyJrZXkiOiAidmFsdWUifQ==', 'base64').toString('utf-8');
    }
}